package co.electriccoin.zcash.ui.screen.onboarding

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.BasicText
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import co.electriccoin.zcash.ui.NavigationRouter
import co.electriccoin.zcash.ui.common.viewmodel.SecretState
import co.electriccoin.zcash.ui.common.viewmodel.WalletViewModel
import co.electriccoin.zcash.ui.design.theme.ZappTheme
import co.electriccoin.zcash.ui.screen.chat.viewmodel.ChatViewModel
import co.electriccoin.zcash.ui.screen.onboarding.view.BioScanScreen
import co.electriccoin.zcash.ui.screen.onboarding.view.MessagingPhaseIntro
import co.electriccoin.zcash.ui.screen.onboarding.view.MessagingSeedPhraseScreen
import co.electriccoin.zcash.ui.screen.onboarding.view.OnboardingDoneScreen
import co.electriccoin.zcash.ui.screen.onboarding.view.TwoFAChoiceScreen
import co.electriccoin.zcash.ui.screen.onboarding.view.TwoFAMode
import co.electriccoin.zcash.ui.screen.onboarding.view.UsernameEntryScreen
import co.electriccoin.zcash.ui.screen.onboarding.view.WalletChoiceScreen
import co.electriccoin.zcash.ui.screen.onboarding.view.WalletPhaseIntro
import co.electriccoin.zcash.ui.screen.onboarding.view.WalletSeedPhraseScreen
import co.electriccoin.zcash.ui.screen.restore.seed.RestoreSeedArgs

/** All steps the Swiss onboarding flow walks the user through. */
private enum class Step {
    MSG_INTRO,
    MSG_USERNAME,
    MSG_SEED,
    WALLET_INTRO,
    WALLET_CHOICE,
    WALLET_SEED,
    SECURE_CHOICE,
    BIO_SCAN,
    DONE,
}

/**
 * Swiss-design post-welcome onboarding orchestrator.
 *
 * Runs after [co.electriccoin.zcash.ui.screen.welcome.view.WelcomeGateView] is
 * dismissed and before the user reaches the tabs shell. Three phases mirror the
 * design canvas:
 * - **Part 1 — Messaging account** (intro, username, seed)
 * - **Part 2 — Wallet** (intro, create/restore/skip, seed)
 * - **Part 3 — Secure Zapp** (biometric/PIN, scan, done)
 *
 * Identity is created on the username step via [ChatViewModel.createIdentity];
 * the recovery phrases shown to the user are the *real* ones generated by the
 * SDK and persisted by [WalletViewModel] (no placeholder words). Wallet restore
 * forwards to the existing [RestoreSeedArgs] flow; an observer auto-advances to
 * the secure step once `secretState` flips to READY so the user lands back
 * inside onboarding rather than on an unfinished tabs shell.
 */
@Composable
fun ZappOnboardingFlow(
    onComplete: () -> Unit,
    walletViewModel: WalletViewModel,
    chatViewModel: ChatViewModel,
    navigationRouter: NavigationRouter,
) {
    var step by rememberSaveable { mutableStateOf(Step.MSG_INTRO) }
    var twoFAMode by rememberSaveable { mutableStateOf(TwoFAMode.Pin) }

    val chatIdentity by chatViewModel.identity.collectAsStateWithLifecycle()
    val walletSeed by walletViewModel.currentSeedWords.collectAsStateWithLifecycle()
    val secretState by walletViewModel.secretState.collectAsStateWithLifecycle()
    val chatError by chatViewModel.errorMessage.collectAsStateWithLifecycle()

    val chatSeed = remember { mutableStateOf<List<String>?>(null) }

    // Once the chat identity exists (post-createIdentity on the username step),
    // pull the real recovery phrase off the SDK so MSG_SEED can render it.
    LaunchedEffect(chatIdentity) {
        if (chatIdentity != null && chatSeed.value == null) {
            chatViewModel.exportSeedPhraseSuspending()?.let { phrase ->
                chatSeed.value = phrase.split(" ").filter { it.isNotBlank() }
            }
        }
    }

    // Wallet-restore lives outside this composable (RestoreSeedScreen). When it
    // completes, secretState flips to READY and the user is popped back into
    // the tabs scaffold, which re-renders this flow at the saved WALLET_CHOICE
    // step. Auto-advance so they don't have to re-tap "Restore" / "Create".
    LaunchedEffect(secretState, step) {
        if (secretState == SecretState.READY && step == Step.WALLET_CHOICE) {
            step = Step.SECURE_CHOICE
        }
    }

    when (step) {
        Step.MSG_INTRO -> MessagingPhaseIntro(
            onBack = onComplete, // back from first step exits onboarding
            onContinue = { step = Step.MSG_USERNAME },
        )
        Step.MSG_USERNAME -> UsernameEntryScreen(
            onBack = { step = Step.MSG_INTRO },
            onContinue = { name ->
                // Idempotent: only create the identity once. Lets the user back
                // out and re-submit without the SDK rejecting a second create.
                if (chatIdentity == null) {
                    chatViewModel.createIdentity(name)
                }
                step = Step.MSG_SEED
            },
        )
        Step.MSG_SEED -> {
            val words = chatSeed.value
            if (words == null) {
                SeedLoadingPlaceholder(error = chatError)
            } else {
                MessagingSeedPhraseScreen(
                    words = words,
                    onBack = { step = Step.MSG_USERNAME },
                    onContinue = { step = Step.WALLET_INTRO },
                )
            }
        }
        Step.WALLET_INTRO -> WalletPhaseIntro(
            onBack = { step = Step.MSG_SEED },
            onContinue = { step = Step.WALLET_CHOICE },
            onSkip = { step = Step.SECURE_CHOICE },
        )
        Step.WALLET_CHOICE -> WalletChoiceScreen(
            onBack = { step = Step.WALLET_INTRO },
            onCreate = {
                walletViewModel.createNewWallet()
                step = Step.WALLET_SEED
            },
            onRestore = {
                navigationRouter.forward(RestoreSeedArgs)
            },
            onSkip = { step = Step.SECURE_CHOICE },
        )
        Step.WALLET_SEED -> {
            val words = walletSeed
            if (words == null) {
                SeedLoadingPlaceholder(error = null)
            } else {
                WalletSeedPhraseScreen(
                    words = words,
                    onBack = { step = Step.WALLET_CHOICE },
                    onContinue = { step = Step.SECURE_CHOICE },
                )
            }
        }
        Step.SECURE_CHOICE -> TwoFAChoiceScreen(
            onBack = { step = Step.WALLET_INTRO },
            onPick = { mode ->
                twoFAMode = mode
                step = if (mode == TwoFAMode.Bio) Step.BIO_SCAN else Step.DONE
            },
        )
        Step.BIO_SCAN -> BioScanScreen(
            onCancel = { step = Step.SECURE_CHOICE },
            onDone = { step = Step.DONE },
        )
        Step.DONE -> OnboardingDoneScreen(
            mode = twoFAMode,
            onEnter = onComplete,
        )
    }
}

/**
 * Brief skeleton shown while the SDK finishes generating the recovery phrase
 * (chat) or persisting the new wallet (wallet). On the happy path this flashes
 * for under a second; if [error] is non-null we surface it instead so the user
 * isn't stuck staring at an indefinite spinner.
 */
@Composable
private fun SeedLoadingPlaceholder(error: String?) {
    val c = ZappTheme.colors
    Box(
        modifier = Modifier.fillMaxSize().background(c.bg),
        contentAlignment = Alignment.Center,
    ) {
        if (error != null) {
            Column(
                modifier = Modifier.fillMaxWidth().padding(horizontal = 28.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
            ) {
                BasicText(
                    text = error,
                    style = ZappTheme.typography.body.copy(
                        color = c.danger,
                        fontSize = 13.sp,
                    ),
                )
                Spacer(Modifier.height(12.dp))
                BasicText(
                    text = "Try going back and submitting again.",
                    style = ZappTheme.typography.body.copy(
                        color = c.textMuted,
                        fontSize = 12.sp,
                    ),
                )
            }
        } else {
            CircularProgressIndicator(color = c.accent)
        }
    }
}
